name: HyperCPU CI/CD Pipeline

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Install GCC
        uses: aminya/setup-cpp@v1
        with:
          compiler: 'gcc'
        
      - name: Install LLVM toolchain
        uses: aminya/setup-cpp@v1
        with:
          compiler: 'llvm'
      
      - name: Install all tools
        uses: aminya/setup-cpp@v1
        with:
          cmake: true
          cppcheck: true
      
      - name: Build and test with GCC
        run: |
          cmake -S. -Bbuild -DCMAKE_C_COMPILER=$(which gcc) -DCMAKE_CXX_COMPILER=$(which g++)
          cd build && make run-all-tests-github
          cd .. && rm -rf build
      
      - name: Build and tests with LLVM
        run: |
          cmake -S. -Bbuild -DCMAKE_C_COMPILER=$(which clang) -DCMAKE_CXX_COMPILER=$(which clang++)
          cd build && make run-all-tests-github
          
        