name: Testing suites

on: [push]

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          submodules: recursive
      
      - name: Configure CMake
        run: |
          cmake -S. -Bbuild

      - name: Build target
        run: |
          cd build
          ninja run-all-tests-github
            